name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            python3-pip \
            openjdk-17-jdk \
            unzip zip git \
            wget curl \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev
          pip3 install --upgrade pip
          pip3 install cython buildozer

      - name: Install Android SDK cmdline-tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip -d latest
          rm sdk-tools.zip
          echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK & accept licenses
        run: |
          source $GITHUB_ENV
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Init buildozer.spec if missing
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          sed -i 's/^requirements.*/requirements = python3,kivy,kivymd,openpyxl,pillow,pyzbar,qrcode/' buildozer.spec
          sed -i 's/^# *android.permissions.*/android.permissions = CAMERA,BLUETOOTH,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE/' buildozer.spec

          if ! grep -q "android.accept_sdk_license" buildozer.spec; then
            echo "android.accept_sdk_license = True" >> buildozer.spec
            echo "android.api = 33" >> buildozer.spec
            echo "android.minapi = 21" >> buildozer.spec
            echo "android.sdk = 33" >> buildozer.spec
            echo "android.ndk = 25b" >> buildozer.spec
            echo "android.build_tools = 33.0.2" >> buildozer.spec
          fi

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: pos_offline_apk
          path: bin/*.apk
